name: Dependency-Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependency-check:
    name: Run OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download OWASP Dependency-Check
        run: |
          VERSION=$(curl -s https://jeremylong.github.io/DependencyCheck/current.txt)
          curl -sL "https://github.com/jeremylong/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip" --output dependency-check.zip
          unzip dependency-check.zip

      - name: Run Dependency-Check Scan
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --project "GitHub Dependency Scan" \
            --scan . \
            --format "HTML" \
            --out ./dependency-check-report

      - name: Upload Scan Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: ./dependency-check-report

      - name: Clean up
        run: rm -rf dependency-check*

